name: build & deploy petclinic java
on: push

jobs:
  maven-build:
    name: build petclinic WAR
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: package mvn
        run: mvn clean package
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: petclinic.war
          path: target/*.war

  deploy-war:
    name: deploy WAR to tomcat
    runs-on: self-hosted
    needs: build petclinic WAR

    steps:
      - name: download artifect
        uses: actions/download-artifact@v4
        with:
          name: petclinic.war
      - name: test artifect donwload
        run: ls -R

