name: build & deploy petclinic java
on: push

jobs:
  maven-build:
    name: build petclinic WAR
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          ref: iede

      - name: build WAR
        run: mvn package

      - name: list current directory
        run: ls -a

      - name: where is the target folder
        run: |
          cd target
          ls -a    
